apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-app
  labels:
    name: example-app
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: example-app
    spec:
      containers:
      - name: example-app
        image: nginx:latest
        ports:
          - containerPort: 80
        env:
          - name: MY_VAR
            value: my_value
