apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: example-app
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: example-app
  minReplicas: 4
  maxReplicas: 50
  targetCPUUtilizationPercentage: 40
