apiVersion: v1
kind: Service
metadata:
  name: example-app
  labels:
    name: example-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    name: example-app
