apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Values.service_name }}-{{ .Values.image.repository }}"
  labels:
    environment: "{{ .Values.service_name }}"
    name: "{{ .Values.service_name }}-{{ .Values.image.repository }}"
    chart: {{ .Values.service_name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Values.service_name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        name: "{{ .Values.service_name }}-{{ .Values.image.repository }}"
        environment: "{{ .Values.service_name }}"
    spec:
      containers:
      - name: container1
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: {{ .Values.service.port }}
