apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service_name }}-{{ .Values.image.repository }}"
  labels:
    environment: {{ .Values.service_name }}
    name: "{{ .Values.service_name }}-{{ .Values.image.repository }}"
    chart: {{ .Values.service_name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Values.service_name }}
spec:
  type: ClusterIP
  ports:
    - name: port1
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    name: "{{ .Values.service_name }}-{{ .Values.image.repository }}"
