{{- if .Values.role_bindings.cluster_admin }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oidc-cluster-admin
subjects:
{{- range .Values.role_bindings.cluster_admin }}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . | quote }}
{{- end }}
{{- end }}
