{{- if .Values.role_bindings.namespaces }}
{{- range $key, $val := .Values.role_bindings.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: k8s-oidc-authenticator
  name: role-grantor-binding-{{ $key }}
  namespace: {{ $key }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
{{- range $val }}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . | quote }}
{{- end }}
---
{{- end }}
{{- end }}
